export const SET_OPTIONS_CATEGORY = 'SET_OPTIONS_CATEGORY';
export const SELECTED_CATEGORYS = 'SELECTED_CATEGORYS';
export const SELECTED_FORM='SELECTED_FORM';
export const ON_CHANGE_KEYWORD='ON_CHANGE_KEYWORD';
export const DISPLAY_RESULT='DISPLAY_RESULT';
export const ON_CHANGE_NAME='ON_CHANGE_NAME';
export const ON_SORT_BY='ON_SORT_BY';
